select * from customer limit 10

--1 What is the total revenue generated by males and females 

select gender, sum(purchase_amount) as revenue
from customer
group by gender

--2 Which customers used a discount but still spent more than the average purchase_amount

select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select AVG(purchase_amount)from customer)

--3 Which are the top 5 products with high average review rating

select item_purchased,ROUND(avg(review_rating)::numeric,2) as "average product review"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--4 Compare the average purchase amount between standard and express shipping

select shipping_type, round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--5 Do subscribed customers spend more? compare average spent and total revenue between subscribers and non subscribers

select subscription_status,
count(customer_id) as "number of customers",
round(avg(purchase_amount), 2) as "average spent",
sum(purchase_amount) as "total_revenue" 
from customer
group by subscription_status

--6 segment customers into new, returning, loyal based on previous purchases and show the count of each segement

WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'new'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
            ELSE 'loyal'
        END AS customer_segment
    FROM customer
)
SELECT
    customer_segment,
    COUNT(*) AS "number of customers"
FROM customer_type
GROUP BY customer_segment
order by "number of customers" desc

--7 what is total revenue contribution by the age groups

select age_group,
sum(purchase_amount) as "total revenue"
from customer
group by age_group
order by "total revenue" desc